services:
  # Backend Service
  - type: web
    name: scriptssor-backend
    env: docker
    repo: https://github.com/hohohin/scriptssor.git
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 10000
      # 腾讯云语音识别配置（需要在Render控制台设置）
      - key: TENCENT_SECRET_ID
        sync: false
      - key: TENCENT_SECRET_KEY
        sync: false
    disk:
      name: temp-storage
      mountPath: /app/temp
      sizeGB: 10
    healthCheckPath: /

  # Frontend Static Site
  - type: web
    name: scriptssor-frontend
    env: static
    repo: https://github.com/hohohin/scriptssor.git
    buildCommand: "cd frontend/scriptCut && npm install && npm install lucide-react && export VITE_API_BASE_URL=https://scriptssor-backend.onrender.com && npm run build"
    publishPath: frontend/scriptCut/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://scriptssor-backend.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600