services:
  - type: web
    name: scriptssor-backend
    env: docker
    repo: https://github.com/hohohin/scriptssor.git
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 10000
      # 腾讯云语音识别配置（需要在Render控制台设置）
      - key: TENCENT_SECRET_ID
        sync: false
      - key: TENCENT_SECRET_KEY
        sync: false
    disk:
      name: temp-storage
      mountPath: /app/temp
      sizeGB: 10
    healthCheckPath: /
    
  - type: web
    name: scriptssor-frontend
    env: docker
    repo: https://github.com/hohohin/scriptssor.git
    dockerContext: frontend
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 10001
      - key: VITE_API_BASE_URL
        value: https://scriptssor-backend.onrender.com